[package]
name = "csv"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.0.4", features = ["derive"] }
csv = "1.1.6"
indicatif = "0.17.0"
